import type { ComposeEnvInput } from './compose-env.ts'

export function resolveComposeEnv(input: ComposeEnvInput): string {
	const autoGenerated: Record<string, string> = {
		SITE_URL: `https://${input.hostname}`,
		COMPOSE_PROJECT_NAME: input.composeProjectName,
		NN_ENVIRONMENT: input.envName,
	}

	const merged = { ...autoGenerated, ...input.secrets }

	return Object.entries(merged)
		.map(([key, value]) => `${key}=${value}`)
		.join('\n')
}
