import { describe, expect, it } from 'vitest'

import { signSupabaseJwt } from './supabase-jwt.ts'

/**
 * Fixed secret + iat used for the hand-computed JWS fixtures below. The
 * literals were produced once with `node:crypto.createHmac('sha256', SECRET)`
 * over the same JSON serialization the implementation uses (insertion-order
 * keys), then pinned. A drift between the function output and these literals
 * means the encoder, the header, or the signature pipeline changed — any of
 * which silently breaks every Supabase API key generated by the deploy.
 */
const SECRET = 'super-secret-jwt-secret-fixed-32'
const IAT = 1_700_000_000

describe('signSupabaseJwt', () => {
	it('produces the hand-computed HS256 JWS for the anon role (no exp)', () => {
		expect(
			signSupabaseJwt(
				{ role: 'anon', iss: 'supabase', iat: IAT },
				SECRET,
			),
		).toBe(
			'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlzcyI6InN1cGFiYXNlIiwiaWF0IjoxNzAwMDAwMDAwfQ.utGz_DEEM-Nt45Vo61vtSHc8ubDauNX-Rpy_TcYl_3U',
		)
	})

	it('produces the hand-computed HS256 JWS for the service_role role with exp', () => {
		expect(
			signSupabaseJwt(
				{
					role: 'service_role',
					iss: 'supabase',
					iat: IAT,
					exp: 1_900_000_000,
				},
				SECRET,
			),
		).toBe(
			'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwiaXNzIjoic3VwYWJhc2UiLCJpYXQiOjE3MDAwMDAwMDAsImV4cCI6MTkwMDAwMDAwMH0.NDCcF5jnilJdex3-r9P0phkxXeoG67fuis778hikZVQ',
		)
	})

	it('emits a JWS whose header segment decodes to {alg:"HS256",typ:"JWT"}', () => {
		const jws = signSupabaseJwt(
			{ role: 'anon', iss: 'supabase', iat: IAT },
			SECRET,
		)
		const headerSegment = jws.split('.')[0]!
		const padded = headerSegment.padEnd(
			headerSegment.length + ((4 - (headerSegment.length % 4)) % 4),
			'=',
		)
		const decodedJson = Buffer.from(
			padded.replace(/-/g, '+').replace(/_/g, '/'),
			'base64',
		).toString('utf8')

		expect(JSON.parse(decodedJson)).toEqual({ alg: 'HS256', typ: 'JWT' })
	})

	it('changes the signature segment when the secret changes', () => {
		const payload = {
			role: 'anon',
			iss: 'supabase',
			iat: IAT,
		} as const
		const a = signSupabaseJwt(payload, SECRET)
		const b = signSupabaseJwt(payload, `${SECRET}-other`)
		const [headerA, payloadA, sigA] = a.split('.')
		const [headerB, payloadB, sigB] = b.split('.')

		expect(headerA).toBe(headerB)
		expect(payloadA).toBe(payloadB)
		expect(sigA).not.toBe(sigB)
	})
})
