import { describe, expect, it } from 'vitest'

import { renderDevVarsExample } from './dev-vars-example.ts'
import { buildWorkerEnvDocument } from './worker-env-document.ts'

import type { ServicesConfig } from '#/config/service-config.ts'
import type { WorkerServiceConfig } from '#/config/types.ts'
import type { WorkerEnvInput } from './worker-env-document.ts'

const service = (
	overrides: Partial<WorkerServiceConfig> = {},
): WorkerServiceConfig => ({
	secrets: [],
	needs: [],
	dependsOn: [],
	entry: 'dist/server/entry.mjs',
	observability: true,
	...overrides,
})

const CDN_BUCKET: ServicesConfig = {
	r2: { buckets: [{ name: 'medias', cdn: true }] },
}

const input = (overrides: Partial<WorkerEnvInput> = {}): WorkerEnvInput => ({
	serviceName: 'web',
	service: service(),
	services: {},
	workerServices: { web: service({ url: 'example.com' }) },
	secretNames: [],
	...overrides,
})

const renderExample = (envInput: WorkerEnvInput): string =>
	renderDevVarsExample(buildWorkerEnvDocument(envInput), envInput.secretNames)

describe('renderDevVarsExample', () => {
	it('lists every var and secret the worker will read, sorted, with empty values', () => {
		expect(
			renderExample(
				input({
					service: service({ needs: ['r2'], url: 'example.com' }),
					services: CDN_BUCKET,
					secretNames: ['BETTER_AUTH_SECRET'],
				}),
			),
		).toBe(
			[
				'# Generated by @nextnode-solutions/worker-types - do not edit.',
				'# Copy the keys you need into .dev.vars, which must NEVER be committed.',
				'',
				'BETTER_AUTH_SECRET=""',
				'R2_BUCKET_MEDIAS=""',
				'R2_BUCKET_MEDIAS_URL=""',
				'R2_ENDPOINT=""',
				'SITE_URL=""',
				'WEB_URL=""',
				'',
			].join('\n'),
		)
	})

	it('lists no binding - a binding is provided by the runtime, never by .dev.vars', () => {
		const rendered = renderExample(
			input({
				serviceName: 'web',
				service: service({ needs: ['r2', 'api'], url: 'example.com' }),
				services: CDN_BUCKET,
				workerServices: {
					web: service({ url: 'example.com' }),
					api: service(),
				},
			}),
		)

		expect(rendered).not.toMatch(/^ASSETS=/m)
		expect(rendered).not.toMatch(/^R2_MEDIAS=/m)
		expect(rendered).not.toMatch(/^API=/m)
	})

	it('keeps the header when the worker reads nothing beyond SITE_URL', () => {
		expect(renderExample(input({ workerServices: {} }))).toBe(
			[
				'# Generated by @nextnode-solutions/worker-types - do not edit.',
				'# Copy the keys you need into .dev.vars, which must NEVER be committed.',
				'',
				'SITE_URL=""',
				'',
			].join('\n'),
		)
	})
})
