import {
	DEFAULT_WORKERS_COMPATIBILITY_DATE,
	WORKERS_COMPATIBILITY_FLAGS,
} from './wrangler-document.ts'

export interface DevWranglerConfigInput {
	readonly projectName: string
	readonly serviceName: string
}

const JSON_INDENT = 2

// Without a config file `wrangler dev` defaults `compatibility_date` to the
// current day, so a worker silently requires a workerd newer than the installed
// one the moment the calendar passes the binary's newest supported date - dev
// then refuses to boot ("requires compatibility date X, but the newest date
// supported by this server binary is X-1"). Pinning the fleet date (the value the
// deploy config already carries) freezes dev's runtime to prod's and stops the
// float; `nodejs_compat` mirrors the deploy flags so dev and prod resolve the
// identical workerd feature set. `main`/`--port` stay on the CLI, so this file
// carries only the runtime pin.
const GENERATED_HEADER = [
	'// Generated by @nextnode-solutions/infrastructure - do not edit.',
	'// Pins the fleet compatibility_date/flags for local `wrangler dev` so dev',
	'// never floats to today and outruns the installed workerd. Regenerate with',
	'// `infra generate-dev-config`.',
].join('\n')

// Build the `wrangler.jsonc` a plain worker's local `wrangler dev` reads. Pure:
// the caller (adapter) writes the returned text to the worker's package root.
export function buildDevWranglerConfig(input: DevWranglerConfigInput): string {
	const body = {
		name: `${input.projectName}-dev-${input.serviceName}`,
		compatibility_date: DEFAULT_WORKERS_COMPATIBILITY_DATE,
		compatibility_flags: [...WORKERS_COMPATIBILITY_FLAGS],
	}
	return `${GENERATED_HEADER}\n${JSON.stringify(body, null, JSON_INDENT)}\n`
}
