import { describe, expect, it } from 'vitest'

import { buildDevWranglerConfig } from './dev-wrangler-config.ts'
import {
	DEFAULT_WORKERS_COMPATIBILITY_DATE,
	WORKERS_COMPATIBILITY_FLAGS,
} from './wrangler-document.ts'

function parseBody(text: string): Record<string, unknown> {
	const start = text.indexOf('{')
	return JSON.parse(text.slice(start))
}

describe('buildDevWranglerConfig', () => {
	it('pins the fleet compatibility date and flags', () => {
		const body = parseBody(
			buildDevWranglerConfig({
				projectName: 'studiobymina',
				serviceName: 'api',
			}),
		)

		expect(body.compatibility_date).toBe(DEFAULT_WORKERS_COMPATIBILITY_DATE)
		expect(body.compatibility_flags).toEqual([
			...WORKERS_COMPATIBILITY_FLAGS,
		])
	})

	it('names the local worker <project>-dev-<service>', () => {
		const body = parseBody(
			buildDevWranglerConfig({
				projectName: 'studiobymina',
				serviceName: 'api',
			}),
		)

		expect(body.name).toBe('studiobymina-dev-api')
	})

	it('leads with a do-not-edit header and ends with a newline', () => {
		const text = buildDevWranglerConfig({
			projectName: 'studiobymina',
			serviceName: 'api',
		})

		expect(
			text.startsWith(
				'// Generated by @nextnode-solutions/infrastructure',
			),
		).toBe(true)
		expect(text.endsWith('\n')).toBe(true)
	})

	it('carries no main so the CLI entry/port stay authoritative', () => {
		const body = parseBody(
			buildDevWranglerConfig({
				projectName: 'studiobymina',
				serviceName: 'api',
			}),
		)

		expect(body).not.toHaveProperty('main')
	})
})
