import { stringEnvKeys } from './worker-env-document.ts'

import type { WranglerDocument } from './wrangler-document.ts'

const GENERATED_HEADER = [
	'# Generated by @nextnode-solutions/worker-types - do not edit.',
	'# Copy the keys you need into .dev.vars, which must NEVER be committed.',
]

/**
 * Render the `.dev.vars.example` for one Worker: every key the deployed worker
 * will read from `env` that a local run must supply itself - the public vars
 * plus the secret names. Bindings are excluded by construction (they live in the
 * wrangler document, not in `vars`): the local runtime provides them, a
 * `.dev.vars` never could.
 *
 * Values are left empty on purpose. A real one would be either the production
 * value - the very drift this block exists to remove - or a local port the infra
 * has no way to know.
 *
 * This makes the keys DISCOVERABLE; it guarantees nothing. Nothing checks that a
 * developer's actual `.dev.vars` is in sync, so `env.<KEY>` can still be
 * undefined locally while the generated types promise a `string`.
 */
export function renderDevVarsExample(
	document: WranglerDocument,
	secretNames: ReadonlyArray<string>,
): string {
	const keys = stringEnvKeys(document, secretNames)

	return [...GENERATED_HEADER, '', ...keys.map(key => `${key}=""`), ''].join(
		'\n',
	)
}
