import { describe, expect, it } from 'vitest'

import { renderWorkerEnvTypes } from './worker-env-types.ts'

import type { ServicesConfig, WorkerServiceConfig } from '#/config/types.ts'
import type { WorkerEnvTypesInput } from './worker-env-types.ts'

const FULL_SERVICES: ServicesConfig = {
	d1: { migrationsFolder: 'drizzle' },
	kv: { namespaces: [{ name: 'sessions' }] },
	queues: { queues: [{ name: 'jobs' }] },
	r2: { buckets: [{ name: 'assets', cdn: true }] },
}

const service = (
	overrides: Partial<WorkerServiceConfig> = {},
): WorkerServiceConfig => ({
	secrets: [],
	needs: [],
	dependsOn: [],
	entry: 'dist/server/entry.mjs',
	...overrides,
})

const input = (
	overrides: Partial<WorkerEnvTypesInput> = {},
): WorkerEnvTypesInput => ({
	serviceName: 'web',
	service: service(),
	services: {},
	serviceNames: ['web'],
	secretNames: [],
	...overrides,
})

// The `readonly <name>: <type>` line the interface must carry.
const member = (name: string, type: string): string =>
	`\treadonly ${name}: ${type}`

describe('renderWorkerEnvTypes', () => {
	it('populates Cloudflare.Env so `import { env }` is typed', () => {
		const dts = renderWorkerEnvTypes(input())

		expect(dts).toContain('declare namespace Cloudflare {')
		expect(dts).toContain('interface Env {')
		expect(dts).toContain('interface Env extends Cloudflare.Env {}')
	})

	it('does not redeclare the cloudflare:workers module', () => {
		expect(renderWorkerEnvTypes(input())).not.toContain(
			"declare module 'cloudflare:workers'",
		)
	})

	it('references @cloudflare/workers-types for the binding globals', () => {
		expect(renderWorkerEnvTypes(input())).toContain(
			'/// <reference types="@cloudflare/workers-types" />',
		)
	})

	it('marks the file generated so it is not hand-edited', () => {
		expect(renderWorkerEnvTypes(input())).toMatch(
			/Generated by @nextnode-solutions\/infrastructure/,
		)
	})

	it('always types SITE_URL as a string var', () => {
		expect(renderWorkerEnvTypes(input())).toContain(
			member('SITE_URL', 'string'),
		)
	})

	it('types an asset-shipping Astro worker with an ASSETS Fetcher', () => {
		const dts = renderWorkerEnvTypes(
			input({ service: service({ entry: 'dist/server/entry.mjs' }) }),
		)

		expect(dts).toContain(member('ASSETS', 'Fetcher'))
	})

	it('omits ASSETS for a worker that ships no static assets', () => {
		const dts = renderWorkerEnvTypes(
			input({ service: service({ entry: 'src/index.ts' }) }),
		)

		expect(dts).not.toContain('ASSETS')
	})

	it('types a bound sibling worker as a Fetcher', () => {
		const dts = renderWorkerEnvTypes(
			input({
				serviceName: 'web',
				service: service({ needs: ['api'] }),
				serviceNames: ['web', 'api'],
			}),
		)

		expect(dts).toContain(member('API', 'Fetcher'))
	})

	it('does not type a self-reference or an undeclared sibling', () => {
		const dts = renderWorkerEnvTypes(
			input({
				serviceName: 'web',
				service: service({ needs: ['web', 'ghost'] }),
				serviceNames: ['web', 'api'],
			}),
		)

		expect(dts).not.toContain(member('WEB', 'Fetcher'))
		expect(dts).not.toContain('GHOST')
	})

	it('types every backing binding with its Cloudflare type', () => {
		const dts = renderWorkerEnvTypes(
			input({
				service: service({ needs: ['d1', 'kv', 'queues', 'r2'] }),
				services: FULL_SERVICES,
			}),
		)

		expect(dts).toContain(member('DB', 'D1Database'))
		expect(dts).toContain(member('KV_SESSIONS', 'KVNamespace'))
		expect(dts).toContain(member('QUEUE_JOBS', 'Queue'))
		expect(dts).toContain(member('R2_ASSETS', 'R2Bucket'))
	})

	it('types the backing public vars alongside their bindings', () => {
		const dts = renderWorkerEnvTypes(
			input({
				service: service({ needs: ['d1', 'kv', 'queues', 'r2'] }),
				services: FULL_SERVICES,
			}),
		)

		expect(dts).toContain(member('D1_DATABASE_ID', 'string'))
		expect(dts).toContain(member('KV_NAMESPACE_SESSIONS_ID', 'string'))
		expect(dts).toContain(member('QUEUE_JOBS_ID', 'string'))
		expect(dts).toContain(member('R2_BUCKET_ASSETS', 'string'))
		expect(dts).toContain(member('R2_BUCKET_ASSETS_URL', 'string'))
		expect(dts).toContain(member('R2_ENDPOINT', 'string'))
	})

	it('omits a backing binding a worker does not declare in needs', () => {
		const dts = renderWorkerEnvTypes(
			input({ service: service({ needs: [] }), services: FULL_SERVICES }),
		)

		expect(dts).not.toContain('D1Database')
		expect(dts).not.toContain('KVNamespace')
	})

	it('types each secret name as a string', () => {
		const dts = renderWorkerEnvTypes(
			input({ secretNames: ['STRIPE_KEY', 'RESEND_API_KEY'] }),
		)

		expect(dts).toContain(member('RESEND_API_KEY', 'string'))
		expect(dts).toContain(member('STRIPE_KEY', 'string'))
	})

	it('emits members sorted by name for a stable file', () => {
		const dts = renderWorkerEnvTypes(
			input({
				service: service({ needs: ['api'] }),
				serviceNames: ['web', 'api'],
				secretNames: ['STRIPE_KEY'],
			}),
		)
		const order = ['API', 'ASSETS', 'SITE_URL', 'STRIPE_KEY'].map(name =>
			dts.indexOf(`readonly ${name}:`),
		)

		expect(order).toEqual([...order].toSorted((a, b) => a - b))
	})
})
