import {
	bindingMembers,
	byCodePoint,
	stringEnvKeys,
} from './worker-env-document.ts'

import type { EnvMember } from './worker-env-document.ts'
import type { WranglerDocument } from './wrangler-document.ts'

const GENERATED_HEADER = [
	'// Generated by @nextnode-solutions/worker-types - do not edit.',
	'// Regenerate with `worker-types gen`; source of truth is nextnode.toml.',
].join('\n')

function stringMembers(names: ReadonlyArray<string>): ReadonlyArray<EnvMember> {
	return names.map(name => ({ name, type: 'string' }))
}

// Every `env.<key>` a worker reads: typed bindings (from the wrangler document),
// public vars, and secrets. Sorted so the emitted file is stable, and deduped by
// name - a binding name that a var also claims is rejected at config load
// (`config/validation/worker-env-keys.ts`), so the collapse is unreachable here.
function collectMembers(
	document: WranglerDocument,
	secretNames: ReadonlyArray<string>,
): ReadonlyArray<EnvMember> {
	const byName = new Map<string, EnvMember>()
	for (const member of [
		...bindingMembers(document),
		...stringMembers(stringEnvKeys(document, secretNames)),
	]) {
		byName.set(member.name, member)
	}
	return [...byName.values()].toSorted((a, b) => byCodePoint(a.name, b.name))
}

/**
 * Render the `worker-configuration.d.ts` for one Worker. The bindings populate
 * `Cloudflare.Env` (declaration-merged onto the empty interface
 * `@cloudflare/workers-types` ships), because that package already types the
 * `cloudflare:workers` module's `env` as `Cloudflare.Env` - a second `declare
 * module 'cloudflare:workers'` here would collide and win with an env missing
 * these bindings. `interface Env extends Cloudflare.Env` exposes the same shape
 * to code that names `Env` directly. This mirrors `wrangler types` verbatim.
 *
 * The bindings are read from the SAME `WranglerDocument` `buildWranglerConfig`
 * deploys (fed placeholder provision outputs, since types need only names), so a
 * binding can never exist in the deployed config yet be missing from the types,
 * or vice versa. Sibling workers are `Fetcher`; D1/KV/R2/Queues get their
 * Cloudflare types; vars and secrets are `string`.
 */
export function renderWorkerEnvTypes(
	document: WranglerDocument,
	secretNames: ReadonlyArray<string>,
): string {
	const members = collectMembers(document, secretNames)
	return [
		GENERATED_HEADER,
		'',
		'/// <reference types="@cloudflare/workers-types" />',
		'',
		'declare namespace Cloudflare {',
		'\tinterface Env {',
		...members.map(member => `\t\treadonly ${member.name}: ${member.type}`),
		'\t}',
		'}',
		'',
		'interface Env extends Cloudflare.Env {}',
		'',
	].join('\n')
}
