import {
	deriveWorkersBackingConfig,
	typesPlaceholderOutputs,
} from './outputs-env.ts'
import { buildWorkerVars } from './worker-vars.ts'
import { buildWranglerConfig } from './wrangler-config.ts'

import type { ServicesConfig } from '#/config/service-config.ts'
import type { WorkerServiceConfig } from '#/config/types.ts'
import type { AppEnvironment } from '#/domain/environment.ts'
import type { WranglerDocument } from './wrangler-document.ts'

export interface WorkerEnvTypesInput {
	readonly serviceName: string
	readonly service: WorkerServiceConfig
	// The [services.*] backing block; bindings/vars are filtered per service by
	// its own `needs`, exactly as the deployed wrangler config filters them.
	readonly services: ServicesConfig
	// Every declared worker name, so a sibling listed in `needs` resolves to a
	// service binding (`Fetcher`) and not a backing binding.
	readonly serviceNames: ReadonlyArray<string>
	// The secret NAMES this worker receives (already expanded: the GLOBAL
	// `[deploy].secrets` pool folded into the service's own). Typed `string`.
	readonly secretNames: ReadonlyArray<string>
}

// The generated `Env` depends only on binding/var/secret NAMES, which are the
// same in every environment and every project. These stand in for the value-side
// inputs `buildWranglerConfig`/`buildWorkerVars` require; every value they
// produce (script names, SITE_URL, the R2 endpoint) is discarded by the renderer.
const TYPES_PROJECT_NAME = 'types'
const TYPES_ENVIRONMENT: AppEnvironment = 'production'
const TYPES_PROJECT_DOMAIN = 'types.invalid'
const TYPES_ACCOUNT_ID = 'types'

const GENERATED_HEADER = [
	'// Generated by @nextnode-solutions/worker-types - do not edit.',
	'// Regenerate with `worker-types gen`; source of truth is nextnode.toml.',
].join('\n')

interface EnvMember {
	readonly name: string
	readonly type: string
}

function bindingMembers(document: WranglerDocument): ReadonlyArray<EnvMember> {
	return [
		...(document.assets
			? [{ name: document.assets.binding, type: 'Fetcher' }]
			: []),
		...(document.services ?? []).map(binding => ({
			name: binding.binding,
			type: 'Fetcher',
		})),
		...(document.d1_databases ?? []).map(binding => ({
			name: binding.binding,
			type: 'D1Database',
		})),
		...(document.kv_namespaces ?? []).map(binding => ({
			name: binding.binding,
			type: 'KVNamespace',
		})),
		...(document.r2_buckets ?? []).map(binding => ({
			name: binding.binding,
			type: 'R2Bucket',
		})),
		...(document.queues?.producers ?? []).map(binding => ({
			name: binding.binding,
			type: 'Queue',
		})),
	]
}

function stringMembers(names: ReadonlyArray<string>): ReadonlyArray<EnvMember> {
	return names.map(name => ({ name, type: 'string' }))
}

// Every `env.<key>` a worker reads: typed bindings (from the wrangler document),
// public vars, and secrets. Deduped (a name cannot span two kinds by
// construction) and sorted so the emitted file is stable run to run.
function collectMembers(
	document: WranglerDocument,
	secretNames: ReadonlyArray<string>,
): ReadonlyArray<EnvMember> {
	const byName = new Map<string, EnvMember>()
	for (const member of [
		...bindingMembers(document),
		...stringMembers(Object.keys(document.vars ?? {})),
		...stringMembers(secretNames),
	]) {
		byName.set(member.name, member)
	}
	return [...byName.values()].toSorted((a, b) => a.name.localeCompare(b.name))
}

/**
 * Render the `worker-configuration.d.ts` for one Worker. The bindings populate
 * `Cloudflare.Env` (declaration-merged onto the empty interface
 * `@cloudflare/workers-types` ships), because that package already types the
 * `cloudflare:workers` module's `env` as `Cloudflare.Env` - a second `declare
 * module 'cloudflare:workers'` here would collide and win with an env missing
 * these bindings. `interface Env extends Cloudflare.Env` exposes the same shape
 * to code that names `Env` directly. This mirrors `wrangler types` verbatim.
 *
 * The bindings are read from the SAME `WranglerDocument` `buildWranglerConfig`
 * deploys (fed placeholder provision outputs, since types need only names), so a
 * binding can never exist in the deployed config yet be missing from the types,
 * or vice versa. Sibling workers are `Fetcher`; D1/KV/R2/Queues get their
 * Cloudflare types; vars and secrets are `string`.
 */
export function renderWorkerEnvTypes(input: WorkerEnvTypesInput): string {
	const backing = deriveWorkersBackingConfig(input.services)
	const outputs = typesPlaceholderOutputs(backing)
	const document = buildWranglerConfig({
		projectName: TYPES_PROJECT_NAME,
		environment: TYPES_ENVIRONMENT,
		serviceName: input.serviceName,
		service: input.service,
		services: input.services,
		outputs,
		cron: [],
		serviceNames: input.serviceNames,
		vars: buildWorkerVars({
			projectDomain: TYPES_PROJECT_DOMAIN,
			environment: TYPES_ENVIRONMENT,
			service: input.service,
			backing,
			outputs,
			accountId: TYPES_ACCOUNT_ID,
		}),
	})

	const members = collectMembers(document, input.secretNames)
	return [
		GENERATED_HEADER,
		'',
		'/// <reference types="@cloudflare/workers-types" />',
		'',
		'declare namespace Cloudflare {',
		'\tinterface Env {',
		...members.map(member => `\t\treadonly ${member.name}: ${member.type}`),
		'\t}',
		'}',
		'',
		'interface Env extends Cloudflare.Env {}',
		'',
	].join('\n')
}
