[project]
name = "monitoring"
type = "app"
internal = true
filter = "@nextnode-solutions/monitoring"

[deploy]
secrets = [
	"CLOUDFLARE_API_TOKEN",
	"CLOUDFLARE_ACCOUNT_ID",
	"HETZNER_API_TOKEN",
	"TS_OAUTH_SECRET",
]
