[project]
name = "monitoring"
type = "app"
internal = true
domain = "monitoring.nextnode.fr"
filter = "@nextnode-solutions/monitoring"

[deploy]
vps = "nn-internals"
secrets = [
	"CLOUDFLARE_API_TOKEN",
	"CLOUDFLARE_ACCOUNT_ID",
	"HETZNER_API_TOKEN",
	"TS_OAUTH_SECRET",
]

[deploy.hetzner]
server_type = "cx33"
location = "nbg1"

[environment]
development = false
