name: Infrastructure

on:
  push:
    branches: [main]
    paths: ["packages/infrastructure/**"]
  pull_request:
    paths: ["packages/infrastructure/**"]

jobs:
  pipeline:
    uses: ./.github/workflows/pipeline.yml
    with:
      config_file: packages/infrastructure/nextnode.toml
    secrets: inherit
